import styled from '@emotion/styled';
import Box from '@mui/material/Box';
import TextField from '@mui/material/TextField';
import Head from 'next/head';
// import {useState} from 'react';

import Footer from '../components/Footer';
import HeaderContact from '../components/HeaderContact';

const FormWrapper = styled.div`
	display: flex;
	flex-direction: column;
	margin: 135px 50px 50px 50px;
	padding: 30px;
	border-radius: 30px;
	background-color: white;
	box-shadow: 0 0 18px -2px rgba(0, 0, 0, 0.07);
	font-weight: 200;
`;

const SubmitButton = styled.button`
	height: 50px;
	margin: 30px 5px 5px 0;
	border: none;
	border-radius: 30px;
	background-color: #61adad;
	color: white;
`;

export default function Contact() {
	// 	const [name, setName] = useState('');
	// 	const [email, setEmail] = useState('');
	// 	const [message, setMessage] = useState('');

	// 	const handleSubmit = e => {
	// 		e.preventDefault();
	// 		const data = {
	// 			name,
	// 			email,
	// 			message,
	// 		};
	// 		console.log(data);
	// 	};

	return (
		<>
			<Head>
				<title>Contact</title>
				<meta name="description" content="Generated by create next app" />
			</Head>
			<HeaderContact />
			<FormWrapper>
				<Box
					component="form"
					sx={{
						'& > :not(style)': {m: 2, width: '20ch'},
					}}
					noValidate
					autoComplete="off"
				>
					<TextField id="name" label="Name" variant="standard" />
					<TextField id="email" label="Mail" variant="standard" />
					<TextField
						id="standard-textarea"
						label="Your Message"
						placeholder="Placeholder"
						multiline
						variant="standard"
					/>{' '}
				</Box>
				<SubmitButton type="submit">Send</SubmitButton>
			</FormWrapper>
			<Footer />
		</>
	);
}
